#! /usr/bin/python2
from __future__ import print_function
import dbus,time

bus = dbus.SessionBus()

f = bus.get_object("org.freedesktop.Notifications","/org/freedesktop/Notifications")

print ("YS Notification Daemon Penetrator")
info = tuple(f.GetServerInformation ())
print ("Server Information: %s, vendor %s, version %s, compliant to spec version %s" % info)
print ("Capabilities: ", ",".join(f.GetCapabilities()))
print ("Trying to open and close a notification.")
id = f.Notify("testsuite",0,"appointment-new","foo","bar",dbus.Array(["default",""]),dbus.Array([""]),50000)
print ("Closing the note in 500ms...")
time.sleep (0.5)
f.CloseNotification (id)
print ("Spawning 15 notifications...")
for i in range(15):
	f.Notify("testsuite",0,"appointment-new","foo %i"%i,"bar",dbus.Array(["default",""]),dbus.Array([""]),5000)
	time.sleep (0.25)

